/* SPDX-License-Identifier: AGPL-3.0-only */
/* Internal linker namespace: avoid ELF symbol interposition with postgres_fdw. */
#ifndef PGWRH_FDW_NAMESPACE_H
#define PGWRH_FDW_NAMESPACE_H
#define set_transmission_modes pgwrh_fdw_set_transmission_modes
#define reset_transmission_modes pgwrh_fdw_reset_transmission_modes
#define process_pending_request pgwrh_fdw_process_pending_request
#define GetConnection pgwrh_fdw_GetConnection
#define ReleaseConnection pgwrh_fdw_ReleaseConnection
#define GetCursorNumber pgwrh_fdw_GetCursorNumber
#define GetPrepStmtNumber pgwrh_fdw_GetPrepStmtNumber
#define do_sql_command pgwrh_fdw_do_sql_command
#define pgfdw_finish_pipeline pgwrh_fdw_pgfdw_finish_pipeline
#define pgfdw_pipeline_submit pgwrh_fdw_pgfdw_pipeline_submit
#define pgfdw_pipeline_sync pgwrh_fdw_pgfdw_pipeline_sync
#define pgfdw_pipeline_process pgwrh_fdw_pgfdw_pipeline_process
#define pgfdw_pipeline_has_room pgwrh_fdw_pgfdw_pipeline_has_room
#define pgfdw_pipeline_ready pgwrh_fdw_pgfdw_pipeline_ready
#define pgfdw_pipeline_events pgwrh_fdw_pgfdw_pipeline_events
#define pgfdw_pipeline_take pgwrh_fdw_pgfdw_pipeline_take
#define pgfdw_pipeline_drain pgwrh_fdw_pgfdw_pipeline_drain
#define pgfdw_pipeline_subcommit pgwrh_fdw_pgfdw_pipeline_subcommit
#define pgfdw_pipeline_abort pgwrh_fdw_pgfdw_pipeline_abort
#define pgfdw_pipeline_disconnect pgwrh_fdw_pgfdw_pipeline_disconnect
#define pgfdw_get_result pgwrh_fdw_pgfdw_get_result
#define pgfdw_exec_query pgwrh_fdw_pgfdw_exec_query
#define pgfdw_report_error pgwrh_fdw_pgfdw_report_error
#define ExtractConnectionOptions pgwrh_fdw_ExtractConnectionOptions
#define ExtractExtensionList pgwrh_fdw_ExtractExtensionList
#define process_pgfdw_appname pgwrh_fdw_process_pgfdw_appname
#define pgfdw_application_name pgwrh_fdw_pgfdw_application_name
#define classifyConditions pgwrh_fdw_classifyConditions
#define is_foreign_expr pgwrh_fdw_is_foreign_expr
#define is_foreign_param pgwrh_fdw_is_foreign_param
#define is_foreign_pathkey pgwrh_fdw_is_foreign_pathkey
#define deparseInsertSql pgwrh_fdw_deparseInsertSql
#define rebuildInsertSql pgwrh_fdw_rebuildInsertSql
#define deparseUpdateSql pgwrh_fdw_deparseUpdateSql
#define deparseDirectUpdateSql pgwrh_fdw_deparseDirectUpdateSql
#define deparseDeleteSql pgwrh_fdw_deparseDeleteSql
#define deparseDirectDeleteSql pgwrh_fdw_deparseDirectDeleteSql
#define deparseAnalyzeSizeSql pgwrh_fdw_deparseAnalyzeSizeSql
#define deparseAnalyzeInfoSql pgwrh_fdw_deparseAnalyzeInfoSql
#define deparseAnalyzeSql pgwrh_fdw_deparseAnalyzeSql
#define deparseTruncateSql pgwrh_fdw_deparseTruncateSql
#define deparseStringLiteral pgwrh_fdw_deparseStringLiteral
#define find_em_for_rel pgwrh_fdw_find_em_for_rel
#define find_em_for_rel_target pgwrh_fdw_find_em_for_rel_target
#define build_tlist_to_deparse pgwrh_fdw_build_tlist_to_deparse
#define deparseSelectStmtForRel pgwrh_fdw_deparseSelectStmtForRel
#define get_jointype_name pgwrh_fdw_get_jointype_name
#define is_builtin pgwrh_fdw_is_builtin
#define is_shippable pgwrh_fdw_is_shippable

#endif
