# Set PGRST_DB_URI in the environment to the controller database URI.
db-schemas = "pgwrh_ui"
db-extra-search-path = ""
db-anon-role = "pgwrh_ui_viewer"
db-pool = 5
server-host = "127.0.0.1"
server-port = 3000
