-- name: master-structure
-- requires: tables

-- pgwrh
-- Copyright (C) 2024  Michal Kleczek

-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.

-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.

-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.

-- Live metadata is also saved at snapshot time, so DROP/DETACH cannot erase
-- the tree that a deployed or rollback-retained configuration still needs.
CREATE VIEW live_shard_structure AS
WITH stc AS (
    SELECT DISTINCT
        st.replication_group_id,
        st.version,
        c.oid::regclass
    FROM
        pg_class c
            JOIN pg_namespace n ON relnamespace = n.oid
            JOIN sharded_table st ON (nspname, relname) = (sharded_table_schema, sharded_table_name)
),
roots AS (
    SELECT *
    FROM stc r
    WHERE NOT EXISTS (SELECT 1 FROM stc WHERE replication_group_id = r.replication_group_id AND version = r.version AND oid <> r.oid AND oid = ANY (SELECT * FROM pg_partition_ancestors(r.oid)))
),
partition_node AS (
    SELECT
        r.replication_group_id,
        r.version,
        n.nspname AS schema_name,
        c.relname AS table_name,
        level,
        pn.nspname AS parent_schema_name,
        p.relname AS parent_table_name,
        CASE
            WHEN level = 0 THEN NULL
            ELSE pg_get_expr(c.relpartbound, c.oid)
        END AS bound,
        CASE
            WHEN t.parentrelid IS NULL THEN NULL
            ELSE pg_get_partkeydef(t.parentrelid)
        END AS parent_partkeydef,
        CASE
            WHEN t.isleaf THEN NULL
            ELSE pg_get_partkeydef(t.relid)
        END AS node_partkeydef,
        t.isleaf AS is_leaf,
        CASE
            WHEN level = 0 THEN cols.root_column_clause
            ELSE NULL
        END AS root_column_clause,
        constraints.local_constraint_clause,
        root_n.nspname AS root_schema_name,
        root_c.relname AS root_table_name
    FROM
        roots r
            JOIN pg_class root_c ON root_c.oid = r.oid
            JOIN pg_namespace root_n ON root_n.oid = root_c.relnamespace
            CROSS JOIN LATERAL pg_partition_tree(r.oid) t
            JOIN pg_class c ON t.relid = c.oid
            JOIN pg_namespace n ON c.relnamespace = n.oid
            LEFT JOIN pg_class p ON t.parentrelid = p.oid
            LEFT JOIN pg_namespace pn ON p.relnamespace = pn.oid
            LEFT JOIN LATERAL (
                SELECT
                    string_agg(
                        format(
                            '%I %s%s%s%s%s',
                            a.attname,
                            format_type(a.atttypid, a.atttypmod),
                            CASE
                                WHEN a.attcollation <> at.typcollation AND a.attcollation <> 0 THEN
                                    format(' COLLATE %I.%I', acn.nspname, ac.collname)
                                ELSE
                                    ''
                            END,
                            CASE
                                WHEN a.attgenerated <> '' THEN
                                    format(
                                        ' GENERATED ALWAYS AS (%s) %s',
                                        pg_get_expr(ad.adbin, ad.adrelid),
                                        CASE a.attgenerated
                                            WHEN 's' THEN 'STORED'
                                            WHEN 'v' THEN 'VIRTUAL'
                                        END
                                    )
                                ELSE
                                    ''
                            END,
                            CASE
                                WHEN a.attgenerated <> '' THEN
                                    ''
                                WHEN a.attidentity = 'a' THEN
                                    ' GENERATED ALWAYS AS IDENTITY'
                                WHEN a.attidentity = 'd' THEN
                                    ' GENERATED BY DEFAULT AS IDENTITY'
                                WHEN ad.oid IS NOT NULL THEN
                                    format(' DEFAULT %s', pg_get_expr(ad.adbin, ad.adrelid))
                                ELSE
                                    ''
                            END,
                            CASE
                                WHEN a.attnotnull THEN ' NOT NULL'
                                ELSE ''
                            END
                        ),
                        ', '
                        ORDER BY a.attnum
                    ) AS root_column_clause
                FROM
                    pg_attribute a
                        JOIN pg_type at ON at.oid = a.atttypid
                        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
                        LEFT JOIN pg_collation ac ON ac.oid = a.attcollation
                        LEFT JOIN pg_namespace acn ON acn.oid = ac.collnamespace
                WHERE
                        a.attrelid = t.relid
                    AND a.attnum >= 1
                    AND NOT a.attisdropped
            ) cols ON TRUE
            LEFT JOIN LATERAL (
                SELECT
                    string_agg(pg_get_constraintdef(con.oid), ', ' ORDER BY con.oid) AS local_constraint_clause
                FROM
                    pg_constraint con
                WHERE
                        con.conrelid = t.relid
                    AND con.conislocal
            ) constraints ON TRUE
    WHERE c.relkind IN ('p', 'r')
)
SELECT * FROM partition_node;
