CREATE OR REPLACE FUNCTION start_rollout(
    _replication_group_id text)
    RETURNS void
    SET SEARCH_PATH FROM CURRENT
    LANGUAGE sql
AS
$$
INSERT INTO replication_group_config_lock (replication_group_id, version)
SELECT
    replication_group_id, version
FROM
    replication_group_config
        JOIN replication_group USING (replication_group_id)
WHERE
    replication_group_id = $1
  AND current_version = target_version AND version <> current_version
ON CONFLICT DO NOTHING;
UPDATE replication_group g
SET target_version = l.version
FROM replication_group_config_lock l
WHERE
    g.replication_group_id = l.replication_group_id
  AND l.version = next_version(current_version)
  AND g.replication_group_id = $1;
$$;

CREATE OR REPLACE VIEW shard_index_definition AS
SELECT
    replication_group_id,
    version,
    schema_name,
    table_name,
    table_name
        || '_'
        || index_template_name
        || '_'
        || substr(md5(index_template_schema || index_template_table_name || index_template), 1, 5) AS index_name,
    index_template
FROM
    shard_assigned_index
        JOIN shard_index_template USING (replication_group_id, version, index_template_schema, index_template_table_name, index_template_name)
;

ALTER TABLE replication_group DROP COLUMN seq_number;

COMMENT ON TRIGGER version_lifecycle_check ON replication_group IS
    $comment$
Makes sure it is only possible to change current_version and target_version according to the following rules:
* If there is no configuration change in progress (ie. current_version = target_version) then it is only possible to change target_version
* If there is configuration change in progress it possible to either
** commit configuration change (ie. set current_version to target_version)
** or rollback configuration change (ie. set target_version to current_version)

It must not be possible to change current_version without changing target_version first.
$comment$;

COMMENT ON TRIGGER check_replication_group_rollout_done ON replication_group IS
    $comment$
# Generated by DeepSeek-R1
This trigger ensures that the replication group is only updated when all nodes have confirmed their configuration for the new version.
It checks both local and remote shards to ensure consistency before allowing an update.
The check_replication_group_rollout_done trigger is designed to ensure that all hosts have confirmed their configuration changes for a given replication group version. When an update occurs, this trigger checks if the new current_version exists in both missing_connected_local_shard and missing_connected_remote_shard tables. If any of these tables lack entries for the new version, it raises an error indicating that not all hosts have completed the configuration rollout. This helps maintain data consistency by preventing updates until all nodes are up to date.

This trigger is crucial because it enforces a rollback mechanism in case there's an inconsistency after the update. By checking before applying any changes and ensuring all necessary configurations are in place, it helps maintain the integrity of the replication group across all participating hosts.
$comment$;

COMMENT ON TRIGGER ping_on_version_change ON replication_group IS
    $$
# Generated by DeepSeek-R1
* This trigger is designed to send a ping check whenever the current or target version changes.
* It ensures that any modifications to the replication group's configuration are properly monitored for consistency and potential issues.
$$;

COMMENT ON FUNCTION make_sure_daemon_started_on_ping_trigger() IS
    'Starts sync daemon if it is not running.';
